name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    # reuse workflow definitions
    uses: ./.github/workflows/test-poetry-xontrib.yml@main
    with:
        xontrib_name: xgit
        lfs: true

